# This workflow will do a clean installation of node dependencies, cache/restore them and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to Production
permissions:
  contents: read

on: 
  push:
    branches: [main]
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [24.2]
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i 

    - name: Vitest Unit Tests
      run: npm run test:unit

    - name: Building the Project
      run: npm run build
      env:
        VITE_MACROTRACKER_API_WEB_URL: ${{ secrets.VITE_MACROTRACKER_API_WEB_URL }}
        VITE_MACROTRACKER_API_KEY: ${{ secrets.VITE_MACROTRACKER_API_KEY }}
        VITE_KASSAL_API_KEY: ${{ secrets.VITE_KASSAL_API_KEY }}
        VITE_EMAILJS_PUBLIC_KEY: ${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}
        VITE_EMAILJS_SERVICE_ID: ${{ secrets.VITE_EMAILJS_SERVICE_ID }}
        VITE_EMAILJS_TEMPLATE_ID: ${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Setup Python environment and install ftpretty
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install ftpretty

    - name: Deploy with FTP
      run: |
        source venv/bin/activate
        python ftp-deploy.py
      env:
        HOST: ${{ secrets.DEPLOY_HOST }}
        USERNAME: ${{ secrets.DEPLOY_USERNAME }}
        PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
